name: Github action Demo
on: push     
jobs:
  action-demo:
    runs-on: ubuntu-latest
    steps:
      - name: check ou the code
        uses: actions/checkout@4
      - name: Print index.html file
        run: cat index.html
