name: context demo
on: push
jobs:
  context-demo:
    runs-on: ubuntu-latest
    steps:
      - name: use context variabls
        run: |
          echo "This workflow is triggered by ${{ github.actor }}"
          echo "This repo name is ${{ github.repository }}"
          echo "The Branch name is ${{ github.ref_name }}"
          
      - name: Print all veribale under github
        run: echo "${{ toJson(github) }}"
        
      - name: Print environment variables
        run: echo "$GITHUB_SHA"
    
