name: Hello world
on:
  push:
    branches:
      - main
      - devlopment
      - 'release/**'
  pull_request:
    branches:
      - main        
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build step
        run: echo "A demo build"
        
    
